logo: /assets/img/round_avarta.png
title: <p align="center"> Thanh M. Nguyen </p>
description:
  <p align="center">
  HealthTech, ML, NLP
  </p>
  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  
  <p align="center">
  <a href="https://www.linkedin.com/in/thanhnguyen5493/" class="fa fa-linkedin"> LinkedIn</a>
  <br><br>
  <a href="https://github.com/ThanhNguyen93" class="fa fa-github"> GitHub</a>
  <br><br>
  <a href="mailto:tnguyen15@hawk.iit.edu" class="fa fa-email"> Email</a>
  </p>   
  
  

  
theme: jekyll-theme-minimal
google_analytics: UA-196727667-1
