logo: /assets/img/round_avarta.png
title: <p align="center"> Thanh M. Nguyen </p>
description:
  <p align="center">
  BioInformatics, HealthTech, ML, NLP
  </p>
  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  
  <p align="center">
  <a href="https://www.linkedin.com/in/thanhnguyen5493/" class="fa fa-linkedin"> LinkedIn</a>
  <br>
  <a href="https://github.com/ThanhNguyen93" class="fa fa-github"> GitHub</a>
  <br>
  <a href="mailto:thanhmnguyen05@gmail.com" class="fa fa-email"> Email</a>
  <a href = "https://github.com/ThanhNguyen93/ThanhNguyen93.github.io/blob/main/pdf/%5BThanhNguyen%5DResume_april_2023.pdf"> Resume</a>
  </p>   
  
  

  
theme: jekyll-theme-minimal
google_analytics: UA-196727667-1
