title: <p align="center"> Thanh M. Nguyen </p>

logo: 

description:
  <p align="center">
  HealthTech, Machine Learning, Natural Langugage Processing
  </p>
  
  <p align="center">
  <a href="https://www.linkedin.com/in/thanhnguyen5493/">LinkedIn</a>
  <a href="https://github.com/ThanhNguyen93">GitHub</a>
  </p>
  

  
theme: jekyll-theme-minimal
