logo: /assets/img/round_avarta.png

title: <p align="center"> Thanh M. Nguyen </p>

description:
  <p align="center">
  HealthTech, Machine Learning, Natural Langugage Processing
  </p>
  
  <p align="center">
  <a href="https://www.linkedin.com/in/thanhnguyen5493/">LinkedIn</a>
  <a href="https://github.com/ThanhNguyen93">GitHub</a>
  </p>   
  
  <div class="author__urls-wrapper">
    <button class="btn btn--inverse">Follow</button>
    <ul class="author__urls social-icons">
      
  <li><a href="https://github.com/ThanhNguyen93" rel="nofollow noopener noreferrer"><i class="fab fa-fw fa-github" aria-hidden="true"></i> GitHub</a></li>
 
  </ul>
  </div>

  
theme: jekyll-theme-minimal
