logo: /assets/img/round_avarta.png
title: <p align="center"> Thanh M. Nguyen </p>
description:
  <p align="center">
  HealthTech, Machine Learning, Natural Langugage Processing
  </p>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  
  <p align="center">
  
  <li><a href="#" class="fa fa-linkedin"></a>
  <a href="https://www.linkedin.com/in/thanhnguyen5493/">LinkedIn</a></li>
  
  <li><a href="#" class="fa fa-github"></a>
  <a href="https://github.com/ThanhNguyen93">GitHub</a></li>
  
  <li><a href="#" class="fa fa-email"></a>
  <a href="mailto:tnguyen15@hawk.iit.edu">Email</a></li>
  
  <li><a href="mailto:tnguyen15@hawk.iit.edu" rel="nofollow noopener noreferrer"><i class="fas fa-fw fa-envelope-square" aria-hidden="true"></i> Email</a></li>
  
  </p>   
  
  

  
theme: jekyll-theme-minimal
google_analytics: UA-196727667-1
